"use client";

import { useState, useCallback, useEffect } from "react";
import Link from "next/link";
import ShareButton from "@/components/ShareButton";
import NewsletterCapture from "@/components/NewsletterCapture";
import RelatedTools from "@/components/RelatedTools";
import { downloadMarkdown } from "@/lib/file-utils";
import { models, estimateTokens } from "@/data/tokenCounterData";
import ModelSelector from "./ModelSelector";
import StatsPanel from "./StatsPanel";
import TokenTips from "./TokenTips";

export default function TokenCounterPage() {
  const [text, setText] = useState("");
  const [selectedModel, setSelectedModel] = useState(models[0]);
  const [shared, setShared] = useState(false);
  const [urlTooLong, setUrlTooLong] = useState(false);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        setText("");
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  // Load state from URL on mount
  useEffect(() => {
    if (typeof window === "undefined") return;
    const params = new URLSearchParams(window.location.search);
    const stateParam = params.get("token");
    if (stateParam) {
      try {
        const decoded = JSON.parse(atob(stateParam));
        if (decoded) {
          if (decoded.text) setText(decoded.text);
          if (decoded.model) {
            const found = models.find((m) => m.name === decoded.model);
            if (found) setSelectedModel(found);
          }
        }
      } catch {
        // Invalid state param, ignore
      }
    }
  }, []);

  const tokens = estimateTokens(text);
  const chars = text.length;
  const words = text.trim() ? text.trim().split(/\s+/).length : 0;
  const lines = text ? text.split("\n").length : 0;

  const contextPercentage = (tokens / selectedModel.context) * 100;
  const estimatedCost = (tokens / 1000000) * selectedModel.inputPrice;

  const getStats = useCallback(() => {
    return `Tokens: ${tokens.toLocaleString()}
Characters: ${chars.toLocaleString()}
Words: ${words.toLocaleString()}
Lines: ${lines.toLocaleString()}
Model: ${selectedModel.name}
Context Used: ${contextPercentage.toFixed(2)}%
Est. Cost: $${estimatedCost.toFixed(6)}`;
  }, [
    tokens,
    chars,
    words,
    lines,
    selectedModel,
    contextPercentage,
    estimatedCost,
  ]);

  const downloadStats = useCallback(() => {
    const content = `# Token Count Analysis

${getStats()}

---
Text analyzed:
\`\`\`
${text.slice(0, 1000)}${text.length > 1000 ? "\n...(truncated)" : ""}
\`\`\`

Generated by substratia.io/tools/token-counter
`;
    downloadMarkdown(content, "token-analysis.md");
  }, [getStats, text]);

  // Share via URL (with length validation)
  const MAX_URL_LENGTH = 2000;
  const shareState = useCallback(async () => {
    const state = { text, model: selectedModel.name };
    const stateStr = btoa(JSON.stringify(state));
    const shareUrl = `${window.location.origin}${window.location.pathname}?token=${stateStr}`;
    if (shareUrl.length > MAX_URL_LENGTH) {
      setUrlTooLong(true);
      setTimeout(() => setUrlTooLong(false), 4000);
      return;
    }
    await navigator.clipboard.writeText(shareUrl);
    setShared(true);
    setTimeout(() => setShared(false), 2000);
  }, [text, selectedModel]);

  return (
    <main className="min-h-screen text-white">
      <div className="container mx-auto px-4 py-12">
        {/* Header */}
        <div className="max-w-4xl mx-auto mb-8">
          <div className="flex items-center justify-between mb-4">
            <Link
              href="/tools"
              className="text-forge-cyan hover:underline text-sm"
            >
              ← Back to Tools
            </Link>
            <ShareButton title="Token Counter - Substratia" />
          </div>
          <h1 className="text-3xl md:text-4xl font-bold mb-2">
            Token <span className="text-forge-cyan">Counter</span>
          </h1>
          <p className="text-gray-400">
            Estimate token count, context usage, and cost for Claude, GPT-4, and
            other models.
          </p>
        </div>

        <div className="max-w-4xl mx-auto grid lg:grid-cols-3 gap-6">
          {/* Input Area */}
          <div className="lg:col-span-2">
            <div className="bg-white/5 border border-white/10 rounded-xl p-4">
              <div className="flex justify-between items-center mb-3">
                <label
                  htmlFor="token-text-input"
                  className="text-sm text-gray-400"
                >
                  Paste your text
                </label>
                <button
                  onClick={() => setText("")}
                  className="text-xs text-gray-500 hover:text-white transition-all flex items-center gap-1"
                >
                  Clear
                  <kbd className="hidden sm:inline px-1.5 py-0.5 text-[10px] bg-white/10 rounded">
                    ⌘K
                  </kbd>
                </button>
              </div>
              <textarea
                id="token-text-input"
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="Paste your prompt, code, or any text here to count tokens..."
                className="w-full h-64 sm:h-80 bg-black/30 border border-white/10 rounded-lg p-4 text-sm font-mono focus:outline-none focus:border-forge-cyan transition-all resize-none"
              />
            </div>

            <ModelSelector
              models={models}
              selectedModel={selectedModel}
              onSelect={setSelectedModel}
            />
          </div>

          <StatsPanel
            tokens={tokens}
            chars={chars}
            words={words}
            lines={lines}
            selectedModel={selectedModel}
            contextPercentage={contextPercentage}
            estimatedCost={estimatedCost}
            text={text}
            getStats={getStats}
            onDownload={downloadStats}
            onShare={shareState}
            shared={shared}
            urlTooLong={urlTooLong}
          />
        </div>

        <TokenTips />

        {/* Related Tools */}
        <RelatedTools currentPath="/tools/token-counter" />

        {/* CTA */}
        <div className="max-w-4xl mx-auto mt-12 text-center">
          <div className="bg-gradient-to-r from-forge-purple/20 to-forge-cyan/20 rounded-2xl p-8">
            <h2 className="text-2xl font-bold mb-3">Running Out of Context?</h2>
            <p className="text-gray-400 mb-6 max-w-xl mx-auto">
              Our free memory tools help you manage context efficiently.
              Snapshot conversations, persist facts across sessions, never lose
              progress.
            </p>
            <Link
              href="/templates"
              className="inline-block px-6 py-3 bg-forge-cyan text-forge-dark font-semibold rounded-xl hover:bg-forge-cyan/90 transition-all"
            >
              Explore Memory Tools
            </Link>
          </div>
        </div>

        {/* Newsletter */}
        <div className="mt-8 max-w-xl mx-auto">
          <NewsletterCapture source="token-counter" compact />
        </div>
      </div>
    </main>
  );
}
