"use client";

import { useState, useCallback, useEffect } from "react";
import {
  ReviewHeader,
  StarRating,
  Recommendations,
  ReviewCtaSection,
  slugify,
} from "@/components/reviews";
import {
  codingAssistants,
  codingAssistantRecommendations,
  codingAssistantCta,
} from "@/data/reviewsData";
import { downloadMarkdown } from "@/lib/file-utils";

export default function AICodingAssistantsPage() {
  const [sharedTool, setSharedTool] = useState<string | null>(null);
  const [copiedVerdict, setCopiedVerdict] = useState<string | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const hash = window.location.hash.slice(1);
    if (hash) {
      setTimeout(() => {
        const element = document.getElementById(hash);
        if (element)
          element.scrollIntoView({ behavior: "smooth", block: "center" });
      }, 100);
    }
  }, []);

  const shareTool = useCallback(async (name: string) => {
    const slug = slugify(name);
    const shareUrl = `${window.location.origin}${window.location.pathname}#${slug}`;
    await navigator.clipboard.writeText(shareUrl);
    setSharedTool(name);
    setTimeout(() => setSharedTool(null), 2000);
  }, []);

  const copyVerdict = useCallback(async (name: string, verdict: string) => {
    await navigator.clipboard.writeText(`${name}: ${verdict}`);
    setCopiedVerdict(name);
    setTimeout(() => setCopiedVerdict(null), 2000);
  }, []);

  const downloadComparison = useCallback(() => {
    const content = `# Best AI Coding Assistants 2026

## Quick Comparison

| Tool | Best For | Pricing | Rating |
|------|----------|---------|--------|
${codingAssistants.map((t) => `| ${t.name} | ${t.bestFor} | ${t.pricing} | ${t.rating}/10 |`).join("\n")}

## Detailed Reviews

${codingAssistants
  .map(
    (t, i) => `### #${i + 1} ${t.name}
**${t.tagline}**

**Pricing:** ${t.pricing} (${t.pricingDetails})
**Best For:** ${t.bestFor}
**Rating:** ${t.rating}/10

**Strengths:**
${t.features.map((f) => `- ${f}`).join("\n")}

**Limitations:**
${t.limitations.map((l) => `- ${l}`).join("\n")}

**Verdict:** ${t.verdict}

---
`,
  )
  .join("\n")}

Generated by substratia.io/reviews/ai-coding-assistants
`;
    downloadMarkdown(content, "ai-coding-assistants-comparison.md");
  }, []);

  return (
    <main className="min-h-screen text-white">
      <div className="container mx-auto px-4 py-12">
        <ReviewHeader
          config={{
            backHref: "/reviews",
            shareTitle: "Best AI Coding Assistants 2026 - Substratia",
            heading: "Best AI Coding Assistants",
            headingAccent: "2026",
            subtitle:
              "A comprehensive comparison of the top AI tools for software development.",
            lastUpdated: "January 2026",
            itemCount: codingAssistants.length,
            author: "Substratia",
            downloadFilename: "ai-coding-assistants-comparison.md",
          }}
          onDownload={downloadComparison}
        />

        {/* Quick Comparison Table */}
        <div className="max-w-5xl mx-auto mb-16 overflow-x-auto">
          <h2 className="text-2xl font-bold mb-6">Quick Comparison</h2>
          <table className="w-full border-collapse">
            <thead>
              <tr className="border-b border-white/20">
                <th className="text-left py-3 px-4">Tool</th>
                <th className="text-left py-3 px-4">Best For</th>
                <th className="text-left py-3 px-4">Pricing</th>
                <th className="text-left py-3 px-4">Rating</th>
              </tr>
            </thead>
            <tbody>
              {codingAssistants.map((tool) => (
                <tr
                  key={tool.name}
                  className="border-b border-white/10 hover:bg-white/5"
                >
                  <td className="py-3 px-4 font-medium">{tool.name}</td>
                  <td className="py-3 px-4 text-gray-400 text-sm">
                    {tool.bestFor}
                  </td>
                  <td className="py-3 px-4 text-forge-cyan">{tool.pricing}</td>
                  <td className="py-3 px-4">
                    <span className="text-forge-cyan font-bold">
                      {tool.rating}/10
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Detailed Reviews */}
        <div className="max-w-4xl mx-auto space-y-12">
          <h2 className="text-2xl font-bold">Detailed Reviews</h2>

          {codingAssistants.map((tool, index) => (
            <div
              key={tool.name}
              id={slugify(tool.name)}
              className="bg-white/5 border border-white/10 rounded-2xl p-6 md:p-8 scroll-mt-24"
            >
              <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4 mb-6">
                <div>
                  <div className="flex items-center gap-3 mb-2">
                    <span className="text-2xl font-bold text-forge-cyan">
                      #{index + 1}
                    </span>
                    <h3 className="text-2xl font-bold">{tool.name}</h3>
                  </div>
                  <p className="text-gray-400">{tool.tagline}</p>
                </div>
                <div className="flex flex-col items-end gap-2">
                  <StarRating rating={tool.rating} />
                  <a
                    href={tool.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm text-forge-cyan hover:underline"
                  >
                    Visit website &rarr;
                  </a>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6 mb-6">
                <div>
                  <h4 className="font-semibold text-green-400 mb-2">
                    Strengths
                  </h4>
                  <ul className="space-y-1">
                    {tool.features.map((feature) => (
                      <li
                        key={feature}
                        className="text-sm text-gray-300 flex items-start gap-2"
                      >
                        <span className="text-green-400 mt-1">+</span>
                        {feature}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <h4 className="font-semibold text-red-400 mb-2">
                    Limitations
                  </h4>
                  <ul className="space-y-1">
                    {tool.limitations.map((limitation) => (
                      <li
                        key={limitation}
                        className="text-sm text-gray-300 flex items-start gap-2"
                      >
                        <span className="text-red-400 mt-1">-</span>
                        {limitation}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="flex flex-col md:flex-row gap-4 mb-4 p-4 bg-white/5 rounded-xl">
                <div className="flex-1">
                  <span className="text-xs text-gray-500 uppercase">
                    Pricing
                  </span>
                  <p className="font-medium">{tool.pricing}</p>
                  <p className="text-sm text-gray-400">{tool.pricingDetails}</p>
                </div>
                <div className="flex-1">
                  <span className="text-xs text-gray-500 uppercase">
                    Best For
                  </span>
                  <p className="font-medium">{tool.bestFor}</p>
                </div>
              </div>

              <div className="border-t border-white/10 pt-4">
                <div className="flex justify-between items-start gap-4">
                  <div className="flex-1">
                    <h4 className="font-semibold mb-2">Our Verdict</h4>
                    <p className="text-gray-300">{tool.verdict}</p>
                  </div>
                  <div className="flex gap-2 shrink-0">
                    <button
                      onClick={() => copyVerdict(tool.name, tool.verdict)}
                      className={`px-3 py-1 text-xs rounded-lg transition-all ${
                        copiedVerdict === tool.name
                          ? "bg-green-500 text-white"
                          : "bg-white/10 hover:bg-white/20"
                      }`}
                    >
                      {copiedVerdict === tool.name ? "Copied!" : "Copy"}
                    </button>
                    <button
                      onClick={() => shareTool(tool.name)}
                      className={`px-3 py-1 text-xs rounded-lg transition-all ${
                        sharedTool === tool.name
                          ? "bg-green-500 text-white"
                          : "bg-forge-cyan/20 hover:bg-forge-cyan/30 text-forge-cyan"
                      }`}
                    >
                      {sharedTool === tool.name ? "Link Copied!" : "Share"}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Recommendations */}
        <div className="mt-16">
          <Recommendations items={codingAssistantRecommendations} columns={3} />
        </div>

        {/* CTA */}
        <div className="mt-16">
          <ReviewCtaSection cta={codingAssistantCta} />
        </div>
      </div>
    </main>
  );
}
