"use client";

import { useState, useCallback, useEffect } from "react";
import {
  ReviewHeader,
  ScoreBar,
  Recommendations,
  ReviewCtaSection,
  RelatedLinks,
  slugify,
} from "@/components/reviews";
import {
  videoGenerators,
  videoGeneratorRecommendations,
  videoGeneratorCta,
  videoGeneratorRelated,
} from "@/data/reviewsData";
import { downloadMarkdown } from "@/lib/file-utils";

export default function AIVideoGeneratorsPage() {
  const [sharedGen, setSharedGen] = useState<string | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const hash = window.location.hash.slice(1);
    if (hash) {
      setTimeout(() => {
        const element = document.getElementById(hash);
        if (element)
          element.scrollIntoView({ behavior: "smooth", block: "center" });
      }, 100);
    }
  }, []);

  const shareGenerator = useCallback(async (name: string) => {
    const slug = slugify(name);
    const shareUrl = `${window.location.origin}${window.location.pathname}#${slug}`;
    await navigator.clipboard.writeText(shareUrl);
    setSharedGen(name);
    setTimeout(() => setSharedGen(null), 2000);
  }, []);

  const downloadComparison = useCallback(() => {
    const content = `# Best AI Video Generators 2026

## Quick Comparison

| Tool | Best For | Max Duration | Pricing | Quality |
|------|----------|--------------|---------|---------|
${videoGenerators.map((g) => `| ${g.name} | ${g.bestFor} | ${g.duration} | ${g.pricing} | ${g.scores.quality}/100 |`).join("\n")}

## Detailed Reviews

${videoGenerators
  .map(
    (g, i) => `### #${i + 1} ${g.name}
**Company:** ${g.company}
**Pricing:** ${g.pricing}
**Best For:** ${g.bestFor}
**Max Duration:** ${g.duration}

**Scores:**
${Object.entries(g.scores)
  .map(([k, v]) => `- ${k}: ${v}/100`)
  .join("\n")}

**Features:** ${g.features.join(", ")}

**Pros:**
${g.pros.map((p) => `- ${p}`).join("\n")}

**Cons:**
${g.cons.map((c) => `- ${c}`).join("\n")}

---
`,
  )
  .join("\n")}

Generated by substratia.io/reviews/ai-video-generators
`;
    downloadMarkdown(content, "ai-video-generators-comparison.md");
  }, []);

  return (
    <main className="min-h-screen text-white">
      <div className="container mx-auto px-4 py-12">
        <ReviewHeader
          config={{
            backHref: "/reviews",
            shareTitle: "Best AI Video Generators 2026 - Substratia",
            heading: "Best AI Video Generators",
            headingAccent: "2026",
            subtitle:
              "A comprehensive comparison of AI video generation tools. Text-to-video, image-to-video, and beyond.",
            lastUpdated: "January 2026",
            itemCount: videoGenerators.length,
            downloadFilename: "ai-video-generators-comparison.md",
          }}
          onDownload={downloadComparison}
        />

        {/* Quick Summary Table */}
        <div className="max-w-4xl mx-auto mb-12 overflow-x-auto">
          <h2 className="text-2xl font-bold mb-6">Quick Comparison</h2>
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-white/10">
                <th className="text-left py-3 px-4">Tool</th>
                <th className="text-left py-3 px-4">Best For</th>
                <th className="text-left py-3 px-4">Max Duration</th>
                <th className="text-left py-3 px-4">Pricing</th>
                <th className="text-center py-3 px-4">Quality</th>
              </tr>
            </thead>
            <tbody>
              {videoGenerators.map((gen) => (
                <tr
                  key={gen.name}
                  className="border-b border-white/5 hover:bg-white/5"
                >
                  <td className="py-3 px-4 font-medium">{gen.name}</td>
                  <td className="py-3 px-4 text-gray-400">{gen.bestFor}</td>
                  <td className="py-3 px-4 text-gray-400">{gen.duration}</td>
                  <td className="py-3 px-4 text-gray-400">{gen.pricing}</td>
                  <td className="py-3 px-4 text-center">
                    <span
                      className={`px-2 py-1 rounded text-xs ${
                        gen.scores.quality >= 90
                          ? "bg-green-500/20 text-green-400"
                          : gen.scores.quality >= 85
                            ? "bg-yellow-500/20 text-yellow-400"
                            : "bg-gray-500/20 text-gray-400"
                      }`}
                    >
                      {gen.scores.quality}/100
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Detailed Cards */}
        <div className="max-w-4xl mx-auto space-y-8 mb-12">
          <h2 className="text-2xl font-bold">Detailed Breakdown</h2>

          {videoGenerators.map((gen, index) => (
            <div
              key={gen.name}
              id={slugify(gen.name)}
              className="bg-white/5 border border-white/10 rounded-xl p-6 scroll-mt-24"
            >
              <div className="flex flex-wrap items-start justify-between gap-4 mb-6">
                <div>
                  <span className="text-forge-cyan text-sm">#{index + 1}</span>
                  <h3 className="text-2xl font-bold">{gen.name}</h3>
                  <p className="text-gray-400">{gen.company}</p>
                </div>
                <div className="text-right">
                  <div className="text-forge-purple font-medium">
                    {gen.pricing}
                  </div>
                  <div className="text-sm text-gray-500">
                    Max: {gen.duration}
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6 mb-6">
                <div>
                  <ScoreBar score={gen.scores.quality} label="Video Quality" />
                  <ScoreBar
                    score={gen.scores.motion}
                    label="Motion Coherence"
                  />
                </div>
                <div>
                  <ScoreBar score={gen.scores.ease} label="Ease of Use" />
                </div>
              </div>

              <div className="mb-6">
                <h4 className="text-sm font-medium text-gray-400 mb-2">
                  Key Features
                </h4>
                <div className="flex flex-wrap gap-2">
                  {gen.features.map((feature) => (
                    <span
                      key={feature}
                      className="text-xs bg-forge-cyan/10 text-forge-cyan px-2 py-1 rounded-lg"
                    >
                      {feature}
                    </span>
                  ))}
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6 mb-4">
                <div>
                  <h4 className="text-sm font-medium text-green-400 mb-2">
                    Pros
                  </h4>
                  <ul className="space-y-1">
                    {gen.pros.map((pro) => (
                      <li
                        key={pro}
                        className="text-sm text-gray-400 flex items-start gap-2"
                      >
                        <span className="text-green-400">+</span> {pro}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <h4 className="text-sm font-medium text-red-400 mb-2">
                    Cons
                  </h4>
                  <ul className="space-y-1">
                    {gen.cons.map((con) => (
                      <li
                        key={con}
                        className="text-sm text-gray-400 flex items-start gap-2"
                      >
                        <span className="text-red-400">-</span> {con}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="flex justify-end">
                <button
                  onClick={() => shareGenerator(gen.name)}
                  className={`px-3 py-1 text-xs rounded-lg transition-all ${
                    sharedGen === gen.name
                      ? "bg-green-500 text-white"
                      : "bg-forge-cyan/20 hover:bg-forge-cyan/30 text-forge-cyan"
                  }`}
                >
                  {sharedGen === gen.name ? "Link Copied!" : "Share"}
                </button>
              </div>
            </div>
          ))}
        </div>

        <Recommendations items={videoGeneratorRecommendations} />
        <ReviewCtaSection cta={videoGeneratorCta} />
        <RelatedLinks links={videoGeneratorRelated} />
      </div>
    </main>
  );
}
